### ISSUE TITLE
Fix floating point comparisson

### ISSUE THREAD

**Issue by xtracko** [crocs-muni/EACirc#143] opened 2015-08-08 15:42 UTC
Runing './eacirc -test' ends with an error due to a floating point comparisson. Follows an output from gdb:
```
Program received signal SIGILL, Illegal instruction.
TestConfigurator::floatingPointEqual (x=0.10000000000000001, y=0.10000000000000001)
    at /home/.../eacirc/eacirc/self_tests/TestConfigurator.cpp:168
168	    CHECK(fabs(x - y) <= 0.000001);
```
Edit: Travis wont catch that.

**Comment by mathius** [comment] 2015-08-30 08:38
Cannot reproduce (neither Travis nor my setup at Win10, VS2013 has the error).

**Comment by xtracko** [comment] 2015-08-30 08:51
I discovered this weird error only on my linux (I dont know which system settings precisely must be used). I can show it to you on my cuda machine. This error even caused eacirc to fail self_test.

**Comment by mathius** [comment] 2015-09-10 20:36
Cannot reproduce on linux systems either (tested multiple configurations).

**Comment by mathius** [comment] 2015-09-16 13:34
Probably won't fix now, will be reopened if necessary.
Added to the list of known bugs: https://github.com/crocs-muni/EACirc/wiki/Known-bugs

**Closed by mathius** 2015-09-16 13:34 UTC
Labels: bug
