### ISSUE TITLE
ROUNDS setting seems to be necessary

### ISSUE THREAD

**Issue by mathius** [crocs-muni/EACirc#135] opened 2015-07-09 08:53 UTC
**Problem:** When specifying ALGORITHMS setting, ROUNDS setting must also be present (contrary to documentation). Otherwise an error is issued.
**Minimal working example:** Delete ROUNDS line from the clean_config_sample.xml
**Ideal solution:** Make ROUNDS truly disposable, sometimes (when running full versions) rounds settings don't make sense.

**Comment by mathius** [comment] 2015-07-12 11:03
Similar situation vice versa (ROUNDS without ALGORITHMS) and both missing.

**Comment by LuboO** [comment] 2015-07-20 10:19
ROUNDS and ALGORITHMS settings can be deleted without error. Error "no valid configs specified to generate" is caused by fact that no valid combinations of algorithm/rounds were specified in config file. Tags alone are not necessary, but when Oneclick generates nothing it issues an error. ROUNDS and ALGORITHMS can be deleted and tag SPECIFIC_ROUNDS can be used instead. 

*Solution:* What is default value to be set when no rounds or algorithms are specified? What do you set in  EACIRC/<specific_project>/ROUNDS tag when you want to run full version of the cipher/alg?

**Comment by mathius** [comment] 2015-07-20 11:05
If no combination is provided, leave the value as set in the EACIRC part of the config. 
* ROUNDS: 1-3, ALGORITHMS: 1-3 generates 9 configs
* ROUNDS: 1-3, ALGORITHMS missing generates 3 configs (using the single algorithm as set in config)
* ROUNDS missing, ALGORITHMS: 1-3 generates 3 configs (using rounds as set in config)
* ROUNDS missing, ALGORITHMS missing generates 1 config (using values set in the config)

**Comment by LuboO** [comment] 2015-07-20 14:38
Fixed in commit 7941df7eab70c31cd49b6cf0434c4a0faacff9bd

**Closed by LuboO** 2015-07-20 14:38 UTC
Labels: bug
